### ISSUE TITLE
[Tasks] Find all of the errors

### ISSUE THREAD

**Issue by maxxnino** [maxxnino/tree-sitter-zig#1]
After this quick and dirty [commit](https://github.com/maxxnino/tree-sitter-zig/commit/21950c37e1c14f6722280da6b90055be39e170d7), which is cover basically every thing in zig lang. And i found the all of the files contain error list below:
#### Fixed in: 4f4f96b9dc53fee7cc6287712714a2a5c6f93c2a
 - [x] [async_fn](https://github.com/maxxnino/tree-sitter-zig/blob/main/corpus/async_fn.zig) #3
 - [x] [cast](https://github.com/maxxnino/tree-sitter-zig/tree/main/corpus/cast.zig) #3
 - [x] [error](https://github.com/maxxnino/tree-sitter-zig/tree/main/corpus/error.zig) #3
 - [x] [eval](https://github.com/maxxnino/tree-sitter-zig/tree/main/corpus/eval.zig) #3
 - [x] [vector](https://github.com/maxxnino/tree-sitter-zig/blob/main/corpus/vector.zig) #3
 - [x] [if](https://github.com/maxxnino/tree-sitter-zig/tree/main/corpus/if.zig) #3
---
#### Fixed in: ce3bb3be6b8c019f8e554752527a9a38403d1e3e
 - [x] slice
```zig
"a"[0.. :0] ++ "b"[0.. :0];
```
---
####  Fixed in: 1c8cfa525125bda83812484379f9ba5ba3e2d837
 - [x] misc #4
---
####  Fixed in: 2d86f784327aac69317c628a36a38995c517292e
 - [x] asm
 - [x] defer
 - [x] null
 - [x] syntax
 - [x] optional
 - [x] union
---
####  Possible false positive
 - [X] [invalid_newline_in_char_literal](https://github.com/maxxnino/tree-sitter-zig/tree/main/corpus/invalid_newline_in_char_literal.zig)
 - [x] [invalid_unattached_doc_comment](https://github.com/maxxnino/tree-sitter-zig/tree/main/corpus/invalid_unattached_doc_comment.zig)
 - [x] [invalid_variadic_fn](https://github.com/maxxnino/tree-sitter-zig/tree/main/corpus/invalid_variadic_fn.zig)

**Comment by matu3ba** [comment]
Cool stuff. I hope you have sufficient test coverage. Especially the precedence of stuff can be very tricky.

You might want to look into the various issues of [this existing zig treesitter grammar](https://github.com/Himujjal/tree-sitter-zig/issues).

**Comment by maxxnino** [comment]
The zig treesitter is in the nvim-treesitter now. If you spot something odd. Or have something want to improve. Just give me a contex or image. I will try to fix it. I think the string comment is working great. As you can see, I already tested the parse with zig-spec test cases. Only small problem in #3

**Comment by maxxnino** [comment]
Yeah, the precedence really tricky. I spent full 3 days, with all the combinations, left and right.... nothing beat the good old friend, all left.

**Comment by maxxnino** [comment]
Good news 😘

**Comment by matu3ba** [comment]
For testing, you can use the compiler files https://github.com/ziglang/zig/tree/master/src 
or in lib/std json os fs
zls files https://github.com/zigtools/zls/blob/3a8d4c7bfb5daeaec5ff55fa8cf39e7fe0f82f9d/src/main.zig#L1424 https://github.com/zigtools/zls/blob/master/src/data/master.zig and https://github.com/zigtools/zls/blob/master/src/analysis.zig.

They are very long and complex or long, which should show potential errors.

**Comment by maxxnino** [comment]
I tested some of the big files in ziglang and zls source code, and it passed all the test
