### ISSUE TITLE
Errors in indentation

### ISSUE THREAD

**Issue by Gaarco** [maxxnino/tree-sitter-zig#10]
I use [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) to show indentation guides in Neovim and this plugin uses treesitter to detect where guides should be placed.
In Zig files the guides are misplaced: how it should be (using regex I think) on the left, how it is (using the treesitter parser) on the right, you can clearly see line 84 and line 100 the indentation guides are not placed correctly when using the parser.
![Screenshot from 2022-02-05 14-05-10](https://user-images.githubusercontent.com/9869590/152643471-5e6d9ec1-8465-4291-ae40-05f00b668734.png)

**Comment by maxxnino** [comment]
I think it the issue with ident-blankline, it happens with other language too. I saw the workaround in lunarvim config
https://github.com/LunarVim/LunarVim/blob/f7cae318e606c3683c532403a87c5fb19b3cea42/lua/lvim/config/settings.lua#L9

**Comment by maxxnino** [comment]
I think it the issue with ident-blankline, it happens with other language too. I saw the workaround in lunarvim config
https://github.com/LunarVim/LunarVim/blob/f7cae318e606c3683c532403a87c5fb19b3cea42/lua/lvim/config/settings.lua#L9

**Comment by Gaarco** [comment]
The workaround doesn't seem to work for me.
I close the issue then, since it isn't caused by the parser.
