### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Andoryuuta** [maxxnino/tree-sitter-zig#13]
Hello!

This project doesn't currently have a license listed. I'm wondering if I can use this project to add Zig diffing into [difftastic](https://github.com/Wilfred/difftastic). AFAIK, this project would need to be licensed under an MIT-compatible license for me to do that.

Could a license be added to the repo? 😄

**Comment by maxxnino** [comment]
Srr for late reply. I'm in middle at moving to a new place. Will check back as soon as posible

**Comment by Andoryuuta** [comment]
No worries at all! I appreciate you taking the time to look at it when you
have time.

Thanks!
