### ISSUE TITLE
FormatSequence doesn't respect precision

### ISSUE THREAD

**Issue by haze** [maxxnino/tree-sitter-zig#19]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/15584994/204062523-1167e3b0-c1e0-4f9a-8e43-0b42b8c504ed.png">

I'm of the party that we either support all of std.fmt's format specifiers when parsing, or none at all (and keep it at StringLiteral)

Does the spec include these?

**Comment by maxxnino** [comment]
When i write format sequence, i don't fully understand how it work. Just slap random thing and wow it work. Good enough for me at that time. I have no clue what's going wrong here. Give me more information.

**Comment by haze** [comment]
The doc comments go into depth for all the possibilities of format options here https://github.com/ziglang/zig/blob/30eb2a1753c41f348f7d5dcf2b9059a51afab5ad/lib/std/fmt.zig#L28

**Comment by maxxnino** [comment]
As i said, i don't fully understand. Good enough for me. If you want to help at least give me some examples, or show me what going wrong here

**Comment by haze** [comment]
In the original post, I have the format sequence `{d:.2}`. The std.fmt doc comment that I linked notes this as
- a format argument of `d`
- no specifier, fill, alignment, or width
- A precision of 2 (print at most 2 decimal places)


Right now you only support a format argument of s. We should support the others
