### ISSUE TITLE
Update README in treesitter to point to your repo.

### ISSUE THREAD

**Issue by matu3ba** [maxxnino/tree-sitter-zig#5]
The README still shows [this URL](https://github.com/Himujjal/tree-sitter-zig) roughly [here](https://github.com/nvim-treesitter/nvim-treesitter#available-modules).
That might mislead people to file issues in the wrong repo.

**Comment by maxxnino** [comment]
Thank you, could you help me with a pull request. Because, I don't have access to the pc right now

**Comment by matu3ba** [comment]
Closing, because already fixed upstream by maintainer [in this commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/03943f9a7cdb82ee5fe4cbbdf6bf16d55d4b9807).
