### ISSUE TITLE
Additional Highlight groups

### ISSUE THREAD

**Issue by haze** [maxxnino/tree-sitter-zig#6]
Hello!

Personally, I like to have in depth syntax highlighting, and I think tree-sitter is a better solution to other regex based solutions. I was wondering if a couple new groups could garner support to improve the flexibility of the groups used for tree sitter highlighting.

Right now, my vim theme (that uses tree-sitter for highlighting) looks like this:

![Zig TreeSitter preview](https://i.imgur.com/EdYl7YT.png)

Here is what my Sublime Text looks like (it uses regex based highlighting)

<img width="1551" alt="Zig Cleanshot Preview" src="https://user-images.githubusercontent.com/15584994/129126916-d9e2658d-83e4-452d-b42a-f6e7dde46e8c.png">

I think the things I would like the most are as follows
- Highlight groups for operators/punctuation (like `*` and `=` and `.*`)
- Highlight groups for function declarations (TSFunction gets mapped to both the function call and function definition)
- Highlight groups for ignored variables (`_ = ...`)

I'm honestly not well versed in tree-sitter so if this isn't possible feel free to close :)

**Comment by maxxnino** [comment]
Actually, we don't need regex. Just need couple of  qquery.and I just don't know which hl group they should belongs too.

**Comment by haze** [comment]
@maxxnino oh no, I wasn’t suggesting that we use regex at all, it’s just that the other highlighting solutions use it.

you can find the official zig sublime package here https://github.com/ziglang/sublime-zig-language

**Comment by maxxnino** [comment]
@haze wow, the sublime text ref is really good. Thank you

**Comment by maxxnino** [comment]
@haze what is your color theme? my color theme get proper systax for function call and definition too
![demo](https://user-images.githubusercontent.com/34153891/129159706-a1e1e511-777d-47d5-9c56-349706711bb0.png)

**Comment by maxxnino** [comment]
I used nvim-treesitter as ref when building query. You can change it, suit for your need. Just change `@function` to whatever query you want

- This is method declaration for struct, enum, union
https://github.com/maxxnino/tree-sitter-zig/blob/cfdf394894565cd9deaa30133ab22bd4c379eb52/queries/highlights.scm#L93-L98

- This is function call
https://github.com/maxxnino/tree-sitter-zig/blob/cfdf394894565cd9deaa30133ab22bd4c379eb52/queries/highlights.scm#L76-L91

- Check the comment
https://github.com/maxxnino/tree-sitter-zig/blob/cfdf394894565cd9deaa30133ab22bd4c379eb52/queries/highlights.scm#L58-L62

**Comment by haze** [comment]
Thank you! I will see if I can throw up a PR sometime this week/weekend.

**Comment by maxxnino** [comment]
@haze what plugin do you use for treesitter. Is it nvim-treesitter or something else

**Comment by haze** [comment]
> @haze what plugin do you use for treesitter. Is it nvim-treesitter or something else

Yes

**Comment by maxxnino** [comment]
I think nvim-treesitter don't have `TSFuncDeclaration` & `TSFuncCall` in the [highlight group](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/highlight.lua). That mean you meed custom query and hl group in nvim-treesitter [config](https://github.com/nvim-treesitter/nvim-treesitter#highlight)

**Comment by haze** [comment]
<img width="678" alt="CleanShot 2021-08-23 at 13 35 31@2x" src="https://user-images.githubusercontent.com/15584994/130491747-23d01399-d8e4-492e-93f0-6c6bb1d9823b.png">

I think we could benefit from having this granularity with our highlight groups (just noticed this while modifying my theme)

**Comment by maxxnino** [comment]
@haze There are two type of highlight. The `#Treesitter` and the regex base highlight or build-in neovim `#Syntax` as the image below.

![lua](https://user-images.githubusercontent.com/34153891/130557450-8cac7c4c-c22f-4093-9335-04cbce081b65.png)

- You can check the souce code in nvim-treesitter [ecma](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/ecma/highlights.scm) and [js](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/javascript/highlights.scm), nothing is called `jsClassBody`, it from another plugin or build-in neovim, i'm not sure. 
- If you want all of the query above. I will write a wiki guide, show all the query you need. 
- I can't submit the [query group](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights) outside of nvim-treesitter support. It'll reject by the CI.
- You can't define you custom query and highlight group with the example below
```lua
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    custom_captures = {
      -- Highlight the @jsClassBody capture group with the "ClassBody" highlight group  in your color scheme.
      ["jsClassBody"] = "ClassBody",
    },
  },
}
```
- Query example
```
(IDENTIFIER) @jsClassBody
```
Btw, the more query you add, the more it's affect the performance.

**Comment by haze** [comment]
Damn, that sucks. `tree-sitter` is nice but it's too barebones for sophisticated highlight work it seems. I'll close this issue an relegate these matters to the zig vim plugin for now. Thanks for all the help and pointers! 😄
