### ISSUE TITLE
Freezes nvim

### ISSUE THREAD

**Issue by dcov** [maxxnino/tree-sitter-zig#7]
As the title mentions, if I enable tree-sitter and open a zig file, it hangs nvim until I close the terminal completely. I've enabled tree-sitter for other languages such as rust, and vimscript, and it works fine on those, which is why I believe it's an issue with this plugin.

System info:
Windows 10
NVIM v0.5.0-dev+1342 (nightly)

**Comment by maxxnino** [comment]
@dcov as you can see. I open a zig file with 24k line of code on my potato laptop (take about 800ms to parse the whole file) https://github.com/nvim-treesitter/nvim-treesitter/issues/1935#issue-1031337835
If you can't give me a minimal config to reproduce  a issue. I can't help

**Comment by oblitum** [comment]
Hey folks, I prefer to stick to the latest release (0.5.1 at the moment). treesitter zig for me simply blows up nvim. Do you practice support to nightlies only?

**Comment by maxxnino** [comment]
This repo just a parser, not a plugin. I think it's a problem with nvim-treesitter, complier, different c abi, wrong query for parser or something else. What do you mean blow up? I need more information in order to help

**Comment by oblitum** [comment]
I get this:

```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 5
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 5
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 5
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 5
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:155: Vim(lua):E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 5
Please check your config for correctness
```

**Comment by maxxnino** [comment]
I guess you using nvim treesitter 0.5 compat branch. If that's the case then the query in that branch is out of sync with parser, which cause a problem, one quick fix is download query/zig in the master nvim-treesitter and put it in your nvim-treesitter on your local machine.

**Comment by oblitum** [comment]
Yes I'm using that branch. I'll pass the _quick fix_ though... thx, just was expecting it to work on last release as this tagged as maintained.
