### ISSUE TITLE
NeoVim freezes when opening a file with the .zig extension

### ISSUE THREAD

**Issue by nextdimension** [maxxnino/tree-sitter-zig#8]
Issue is in the title.
I've confirmed this on macOS and Linux running Neovim nightly and stable.
Open nvim with an empty buffer and run :checkhealth nvim_treesitter with only this parser installed will crash nvim.

**Comment by maxxnino** [comment]
I got error too, not because of this commit. I'm investigating. I'll fix in the weekend. I have 12h working tomorow

**Comment by Mnohem** [comment]
Has anyone found a fix or workaround for this yet? This also affects the helix editor.

**Comment by maxxnino** [comment]
Good new guys https://github.com/neovim/neovim/pull/16606#pullrequestreview-829735327. Without it, i really have no clue how to fix it

**Comment by maxxnino** [comment]
Solved with 
https://github.com/nvim-treesitter/nvim-treesitter/issues/2049#issuecomment-993853458
