### ISSUE TITLE
`c_void` to `anyopaque`

### ISSUE THREAD

**Issue by Gaarco** [maxxnino/tree-sitter-zig#9]
`c_void` has been renamed to `anyopaque` since the recent 0.9 release.
I was wondering if you could update it, I'd do it myself but I'm afraid I have no idea how treesitter works.

**Comment by maxxnino** [comment]
I already updated and test on my local machine for about 1 week. I will push new commit on monday next week.

**Comment by maxxnino** [comment]
@Gaarco I pushed new commit, in neovim just run `:TSInstall zig` reinstall parser
